### ISSUE TITLE
Day 1 Lesson: R for plotting using ggplot2

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#1]
File path: `_episodes_rmd/01-r-plotting.Rmd`

Goals for end of session (using RStudio):
1. Be able to read in data, plot it, and save the plots
1. Have data, code, plot
1. Understand basics of “grammar of graphics” - i.e. layering in ggplot (not necessarily the vocab, but the concepts)

Topics covered: 
- [x] Overview of R Studio
- [x] Reading in data
- [x] Plotting with ggplot
- [x] Using variables, basic data types (numeric, character, data.frame)
- [x] Saving plots
- [ ] Possibly a few other dplyr functions
- [x] Commenting code?

Other requirements:
- [ ] Total time: 2hr30min
- [x] Bite-sized practice exercises throughout
- [x] Glossary of terms/vocab at end of lesson
- [x] Uses [gapminder dataset](https://github.com/UMSWC/curriculum/blob/gh-pages/data/gapminder_data.csv)

**Comment by kelly-sovacool** [comment]
i'm working on #7
