### ISSUE TITLE
Write bonus exercises

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#10]
See the corresponding lesson issues to see what topics are being covered. Based on those, write bonus bite-sized exercises that learners can use to practice what they've learned.

Lessons: 
- #1 R for plotting 
- #2 Unix shell
- #4 Git/GitHub
- #6 R for data analysis
- #7 R markdown

Also can do bonus exercises for future directions. Example topics: #9.

**Comment by kelly-sovacool** [comment]
We should probably close this issue now that we have issues open for bonus exercises we'd like to add.
