### ISSUE TITLE
Top half moving content 

### ISSUE THREAD

**Issue by mayalapp** [UMSWC/curriculum#121]
- [x] arrange 
- [x] select helper functions
- [x] min & max lifeExp summarize (instead just add max(year) to one of the mean 

Exercises (delete or make bonus): 
- [x] Practice using %>%
- [x] Variable names with characters or spaces

**Comment by dkcoxie** [comment]
Breakpoint for putting bonus content = reshaping data

**Comment by dkcoxie** [comment]
Unresolved content moves can be added to new issue as not all points in list have been resolved.
