### ISSUE TITLE
Day 1 Lesson: The Unix Shell

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#2]
File path: `_episodes/02-unix-shell.md`

Goals for end of session:
- Be able to navigate the shell
- Have a project directory structure
- Understand the usefulness of the shell 

Topics covered:
- [x] Pwd, cd, ls, mkdir
- [x] Man, less, nano
- [x] Maybe: cp, mv, rm
- [x] Text vs. binary file -- can use csv pdf as examples

Other requirements:
- [ ] Total time: 1hr15min
- [ ] Bite-sized practice exercises throughout
- [ ] Glossary of terms/vocab at end of lesson
- [ ] Use files from R plotting lesson (#1)

NOTE:
- Useful resource: Zena's shell notes https://gist.github.com/zenalapp/78118b3ff5b5427bfe4c9bb0dd1af52a
- Be sure to call it "the unix shell", _not_ bash. The concepts are the same whether using bash, zsh, or other common shell languages. Users with the latest macOS version have zsh by default instead of bash.

**Comment by courtneyarmour** [comment]
link to paper talking about structure of computational biology projects: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424

**Comment by zenalapp** [comment]
The default shell thingy for the SWC template is Bash - not sure it's worth figuring out how to change it. Only mentioning because we discussed not explaining bash specifically.

**Comment by kelly-sovacool** [comment]
> The default shell thingy for the SWC template is Bash - not sure it's worth figuring out how to change it. Only mentioning because we discussed not explaining bash specifically.

My plan is to edit the template to rename it as "Shell" instead of "Bash". If you keep using `.language-bash` for now I'll do a search-and-replace-all for that later after I fix it.

**Comment by zenalapp** [comment]
Also thinking about not teaching `rm` because we don't want them to accidentally delete their day 1 morning stuff. A little worried about them somehow messing it up anyways....let me know if anyone has thoughts. We could, e.g., have them copy/zip it using the GUI first so they have it just in case something goes terribly wrong?
