### ISSUE TITLE
Write setup instructions for learners

### ISSUE THREAD

**Issue by kelly-sovacool** [UMSWC/curriculum#3]
File: `setup.md`. Can stitch together from [existing SWC lessons](https://github.com/swcarpentry/swcarpentry#lesson-repositories). 

For each tool, need setup instructions for each OS (Linux, macOS, Windows)
- [x] unix shell
  - [x] discuss WSL on Windows >= 10 vs. [git for windows](https://gitforwindows.org/).
- [x] git
- [x] R
- [x] R Studio

Should include:
- [x] What to install, how to install it, and how to check if it works.
- [x] Blurb about difference between R & RStudio.
- [x] Download gapminder data as a zip (un-report.zip), move zip to Desktop, unzip it.
- [x] Make test script that user has to run to get workshop link to make sure they have everything installed (R/RStudio, R version & tidyverse version, unix terminal) & correct version numbers.
    - [x] create check_setup.R script
    - [x] write instructions for test script

**Comment by pschloss** [comment]
The test example could also insure that they have gapminder in the correct place too

**Comment by pschloss** [comment]
[Here's the instructions](http://www.riffomonas.org/code_club/setup-instructions) that I've made to help learners get set up with R/RStudio. I have them email me the plot at the very end. Would be good to...
* use gapminder data to generate the plot so we know they have the gapminder data in the right place. 
* insert code into the figure so you know the version of R, RStudio, and tidyverse they are using 

[Here are good instructions](https://itsfoss.com/install-bash-on-windows/) I've used for setting up bash in Windows 10

**Comment by kelly-sovacool** [comment]
Additional step I forgot to include in the description: learners will also need to create a GitHub account if they haven't already.

**Comment by barnierc** [comment]
Just FYI, I have a windows machine with both cygwin and gitbash installed so if you need any guinea pigs, I could test out setup instructions with either of those or wsl.

**Comment by justbennet** [comment]
Thanks, @barnierc

**Comment by kelly-sovacool** [comment]
Resolved by #43
