### ISSUE TITLE
un-zip should have all datasets in it 

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#45]
- [ ] gapminder_1997.csv (R for plotting)
- [ ] gapminder_data.csv (R for data analysis)
- [ ] co2-un-data.csv (R for data analysis)
- [ ] rnd-un-data.csv (R markdown exercise)

Any others I'm forgetting?

**Comment by kelly-sovacool** [comment]
@zenalapp are these all in the `data/` dir, or can you put them there of not?

**Comment by zenalapp** [comment]
They're all in `data/` on this branch: r-markdown-exercise

Haven't merged it into gh-pages yet, so the rnd dataset isn't there yet.
