### ISSUE TITLE
Schedule times need to be fixed

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#48]
Not super important for the workshop, but it is confusing.

https://umswc.github.io/curriculum/

**Comment by kelly-sovacool** [comment]
Filling in the estimated teaching time in the YAML headers of each markdown file will fix it.

**Comment by kelly-sovacool** [comment]
Right now they're all `teaching: 0`

**Comment by kelly-sovacool** [comment]
We should probably just fill in the estimated teaching time based on our aspirations from https://github.com/UMSWC/curriculum#workshop-schedule
