### ISSUE TITLE
Write intro to workshop

### ISSUE THREAD

**Issue by kelly-sovacool** [UMSWC/curriculum#5]
File: `_episodes/00-welcome.md`

This is more for the lead instructor's benefit than anyone else's, but it should be written with learners as the audience.

Topics covered:
- [ ] Code of conduct
- [ ] What we’re covering & overall goals
- [ ] What SWC/DC is
- [ ] Bathrooms (in person)
- [ ] Stickies (in person) or how to get help in Zoom
- [ ] Encourage questions
- [ ] Etherpad
- [ ] Introductions (instructors, helpers, participants)
- [ ] Introduce the overall "goal" of the workshop? (i.e. write a report to the UN about carbon dioxide emissions or whatever we decide to do exactly?)

**Comment by pschloss** [comment]
For virtual stickies, zoom has a variety of buttons that make good surrogates - go slower/go faster work well
