### ISSUE TITLE
Day 2 Lesson: R for data analysis

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#6]
File path: `_episodes_rmd/04-r-data-analysis.Rmd`

Goals for end of session:
- Understand how to clean, subset, join (using different dataset - e.g. world happiness),  and summarize your data using dplyr functions.
- Documentation.
- Gain comfort with using git/GitHub for version control while working on a project.
- Understand how to run R from the command line

Topics covered:
- [x] Dplyr functions (e.g. group_by, summarize, filter, select, rename, mutate, join)
- [ ] Continued practice with git/GitHub
~- [ ] How to get help with R functions (either here and/or in R for plotting - maybe already covered?)~ -- covered in R for plotting
~- [ ] Running R scripts from the command line with the Unix Rscript command~ -- do this in future directions instead. 

Other requirements:
- [ ] Total time: 2hr45min
- [ ] Bite-sized practice exercises throughout
- [ ] Glossary of terms/vocab at end of lesson
- [x] Uses gapminder data
- [x] Integrates another dataset that's not gapminder (e.g. country happiness index)

**Comment by pschloss** [comment]
Our notes and lesson development: https://pad.carpentries.org/umichswc_curriculum_sprint_2020_R2
