### ISSUE TITLE
Tibble output on website doesn't render nicely

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#65]
No idea how to fix this...

**Comment by kelly-sovacool** [comment]
The markdown files appeared to have all those extra characters when GitHub Actions creates them. The current fix is to run `make site` (or `make _episodes/filename.md` for just one lesson file) locally after editing R Markdown lesson files. Hopefully I'll be able to figure out what's wrong with it when GitHub Actions does it later.
