### ISSUE TITLE
Day 2 Lesson: Writing reports using R markdown

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#7]
File path: `_episodes_rmd/05-r-markdown.Rmd`

Some ideas: https://raw.githubusercontent.com/um-dang/literate-programming-r-markdown/master/literate-programming-r-markdown.Rmd

Goals for session:
- Have report in R markdown (based on objective outlined at beginning of workshop)
- Put report on GitHub
- Major collaborative exercise at the end to tie everything together (#8)

Topics covered:
- [x] Why use R markdown. (Circle back to reproducibility.)
- [x] Basics of markdown
- [x] Including code
- [x] Including images (?)
- [x] More integration of git/GitHub

Other requirements:
- [x] Total time: 1hr30min
- [x] Bite-sized practice exercises throughout
- [ ] Glossary of terms/vocab at end of lesson
- [x] Uses gapminder dataset

**Comment by pschloss** [comment]
One idea for images... there's a [database of national flags](https://data.world/pbi/country-flag-database-from-wikipedia) that learners could use to join with the gap minder data or to filter to get a set of countries they're interested in

**Comment by juleka** [comment]
Removed some TODOs from the file as i am not sure we can address them at this point

TODO:
- [ ] check with R analysis team for the CO2 data format after that part of workshop
- [ ] cut down number of questions (there is likely not enough time for all of the following)
- [ ] check with R plotting and stats to make sure the contents has been covered before the exercises
