### ISSUE TITLE
Update to R for Data Analysis Lesson 

### ISSUE THREAD

**Issue by mayalapp** [UMSWC/curriculum#75]
- [x]  Changes to piping/summarize 
     - Changed order of introducing piping: used summarize without piping first (summarize(data, mean(lifeExp))) then changed it to piping to explain how piping lets you pipe in as the first argument
     - "averageLifeExp" for column name instead of "average" (more informative) 
     - note that "summarise" is identical 
     - New exercise with summarize (e.g. find average population using %>% and summarize or something similar) 
- [x] Exercises taught but not in curriculum: 
     - mutate to find population in millions
     - select the columns needed for the reshaping section 
     - selecting columns for co2 dataframe
- [x] Content taught but not in curriculum:
     - #64 write_csv( ) for final gapminder_co2 dataframe
     - add, commit, push to git  before data cleaning and at end of lesson (if time)
- [x] Variable name changes and save file 
     - Change "total" to "total_emissions" and "per_capita" to "per_capita_emissions" 
     - #70 Change gapminder_data to gapminder_data_2007 for second part of lesson
     - #105 Save file as un_data_analysis.R at beginning of lesson (after opening script)

**Comment by mayalapp** [comment]
I'm working on "Exercises taught but not in curriculum"

**Comment by dkcoxie** [comment]
I've created a separate branch to address issues listed below "Changes to piping/summarize"

**Comment by dkcoxie** [comment]
Created new branch for "Variable name changes and save file", will include changes addressing issues 70 & 105
