### ISSUE TITLE
Day 2 final exercise: Collaborative small group exercise

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#8]
File path: `_episodes_rmd/05-r-markdown.Rmd`

This exercise will go at the bottom of the R markdown lesson.

Goals for end of session:
- More comfort with topics learned over course of workshop.
- Report on GitHub.

Topics covered:
- [x] Using R markdown
- [x] Cleaning/analyzing data
- [x] Plotting data
- [x] Working in the Unix shell
- [x] Using git and GitHub
- [x] Sharing code/report?
- [x] Some with gapminder dataset, some with new dataset

Other requirements:
- [ ] Total time: 45min

To do:
- [x] Organize by old vs. new dataset.
- [x] Organize from less hard to more hard.
- [x] Have a reasonable number of exercises, plus bonus exercises.
- [ ] Get formatting correct.

**Comment by kelly-sovacool** [comment]
Revisions:
- [ ] re-explain git clone, add, commit, push, & pull in more detail.
- [ ] make sure it makes sense for people who weren't in the same group during the github exercise.

**Comment by kelly-sovacool** [comment]
Moved these un-checked tasks to #88
