### ISSUE TITLE
Make images show up for R plotting lesson

### ISSUE THREAD

**Issue by zenalapp** [UMSWC/curriculum#99]
Images aren't showing up. Fix this. Look at how GitHub lesson does it.

**Comment by MrFlick** [comment]
Which images are you referring to? It seems like most of them are available at https://umswc.github.io/curriculum/01-r-plotting/index.html. I only noticed the animated GIF seems to be missing.

**Comment by zenalapp** [comment]
The hard-coded images (e.g. of R Studio)

**Comment by MrFlick** [comment]
Ah yes, I see it now. So for example on line 100 
```
![](01-r-plotting-assets/initial_rstudio.png)
```
Right now it seems we have our images in `/_episodes_rmd/01-r-plot-assets` but those aren't going anywhere when the rmd is compiled and the site is built. I moved all those files into /fig/r-plotting and updated the links in PR #129
